project_id = "ugibxiaqrvrmxaniylaz"

[functions.ocr-document]
verify_jwt = false

[functions.extract-reservation]
verify_jwt = false

[functions.generate-tips]
verify_jwt = false

[functions.suggest-restaurants]
verify_jwt = false

[functions.generate-tasks]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.extract-itinerary]
verify_jwt = false

[functions.trip-members]
verify_jwt = true
